language: rust

addons:
  apt:
    packages:
      libusb-1.0-0-dev
      libusb-1.0-0

rust:
  - nightly
  - stable

cache: cargo

install:
  - rustup target add thumbv7m-none-eabi

script:
  - ./cargo-build.sh
